ttytm/wthrr-the-weathercrab

src/modules/params.rs

The --unit flag doesn't get checked correctly so you can't set the unit to fahrenheit. This is because the original code checks if that arg is *not* empty when if should be checking if it's empty.
Also, it may be helpful to use an enum, rather than passing strings around. I believe it will make the code clearer on what is being passed around and if you need to make changes to how temperatures are displayed, you only have to change a method on said enum, rather than finding/modifying it in different functions.

Fix prep_unit for fahrenheit

---

src/modules/args.rs
src/modules/params.rs

The default case for units in clap makes the check for units later return true even if no unit arguments were supplied.

Fixed Fahrenheit config option not being detected

---

src/modules/display/forecast.rs
src/modules/locales/localization.rs

introduced in adca0602db76cb566f8df6895935ba8ec262e48a
Comparison logic was wrong, which caused the locale to be translated every time from English to English. Be advised that this means generating the translation is really slow, which is unaffected by this fix.
Fixes #62.

🐛 fix performance regression when translating from en to en

---

README.md
src/modules/args.rs
src/modules/display/current.rs
src/modules/display/hourly.rs
src/modules/params/units.rs
src/modules/weather.rs
wthrr.ron

Implements probability of precipitation as configurable unit.
Since this is the most commonly used, it is set as the default.
closes #65

feat: add % chance of precipitation unit as default

---

src/modules/config.rs
src/modules/params.rs

Fixes https://github.com/tobealive/wthrr-the-weathercrab/issues/81. `C:\Users\<user>\AppData\Roaming\weathercrab\` won't exist on first run so creating the `config` directory will fail.
File/folder creation/writes can legitimately fail due to file system issues (e.g. permissions) so I converted those calls to return `Result`'s instead of panic.

Fix config directory creation failure

---

src/modules/location.rs

Currently the weather for Berlin will always be displayed if OSM fails.

Fix hardcoded Berlin in geolocation

---

src/modules/api.rs
src/modules/location.rs
src/modules/mod.rs

This is an initial suggestion based on the discussion in #86.  I will add some explanations on the changes in a review.  To show the basic ideas of the trait based approach, I refactored the location determination using the newly introduced API trait as an example.

[Enhancement] Add API Trait

---

INSTALL.md

This PR fixes #89 by adding a new paragraph to `INSTALL.md`.

[Documentation] Add Information on `cargo install --git`

---

src/main.rs
src/modules/api.rs
src/modules/args.rs
src/modules/config.rs
src/modules/display/border.rs
src/modules/display/current.rs
src/modules/display/day.rs
src/modules/display/graph.rs
src/modules/display/gui_config.rs
src/modules/display/historical.rs
src/modules/display/hourly.rs
src/modules/display/product.rs
src/modules/display/utils.rs
src/modules/display/weathercode.rs
src/modules/display/week.rs
src/modules/display/wind.rs
src/modules/forecast.rs
src/modules/localization.rs
src/modules/location.rs
src/modules/params.rs
src/modules/units.rs
src/modules/weather.rs

these might not all be of interest, so i've split them into separate commits for ease of review

address a bunch of pedantic clippy lints

---

src/modules/display/product.rs
src/modules/forecast.rs

* Use a wrapper for the pub fn and pass current day as arg.
* Removes need to use `#[cfg(test)]` / `#[cfg(not(test))]` attrs to mock the current weekday to make it testable.
* Updates naming / comments.

♻️ refactor `get_forecast_indices()`

---

flake.nix

Resolves #115.
Disables `modules::localization::tests::translate_string` and `modules::location::tests::geolocation_response` when building.

Updated flake.nix to exclude network tests

---

.github/workflows/tarpaulin.yml

This PR allows for faster code coverage determination due to the omission of the GitHub Caching Action.  Tarpaulin is now fetched directly as binary from its project.  This saves about three minutes.  Thus, I decided to suggest to running the code coverage determination always, i.e. on each PR.

[Enhancement] Remove GitHub Caching Action

---

src/modules/display/wind.rs

This PR is related to #121 and applies less ambiguous wind direction arrows.  Despite also having emojis for arrows, there are furthermore some characters available which are natural part of the default keyboard layouts of Linux systems.  These arrows are known to be less ambiguous than the emoji arrows, which are sometimes rendered as Asian characters, due to having lower UTF-8 character codes.
(Drafted due to the typo in the commit message:  "ambigous".)

[Enhancement] Less Ambiguous Wind Direction Arrows

---

src/modules/args.rs
src/modules/forecast.rs

This PR aims to fix #132 by providing a new CLI option to ask for "tomorrow".
Examples:
- `wthrr London -f t`
- `wthrr London -f to`
- `wthrr London -f tom`
- `wthrr London -f tomorrow`
The possible values are oriented on the current implementations; users are always allowed to spell out the whole names of the (week) days as well as to abbreviate it by one, two, or three (initial) letters.

[Enhancement] Add Forecast for Tomorrow

---

src/modules/args.rs

This PR fixes a minor bug due to which `wthrr -f tomorrow` led to an error; "tip: a similar value exists: '(t)omorrow'".
When I defined the query for the succeeding day, I forgot to add the word itself as an allowed alias value.  The command still works as it should, so this is not a critical bug.  But I would like to correct my mistake now that I noticed it.
I am sorry.

[Bugfix] Enable `wthrr -f tomorrow`

---

.github/dependabot.yml

These are the changes I mentioned in #143.
If you make your way through the definitions of the functions called in https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L62-L73, you will see that we should achieve the desired effect without the explicit prefix, as well.

:bug: remove commit message settings in `dependabot.yml`

---

.github/dependabot.yml

Because I will take care about the version updates suggested by Dependabot from now on, I made me the default assignee of its PRs.  This is also how you adjusted the list of assignees for #152 and #153 manually, @tobealive.

:robot: change default assignee for Dependabot PRs

---

wthrr.ron

This PR removes obsolete trailing white spaces (TWS) in the configuration file.  Furthermore, it shall be tested whether the GHA linter will accept the recent changes.

🐛 remove TWS in wthrr.ron

---

Cargo.lock

This PR updates the indirect dependencies `openssl` and `openssl-sys`.

⬆️ update `openssl` and `openssl-sys`

---

.github/workflows/lint.yml

This PR reduces the maintenance effort for the GHA workflow linter by calling its Docker image directly with the version being set to `latest` instead of applying the wrapper around it.
@tobealive, if you prefer to install updates for the linter by merging PRs, we might need to switch to Renovate as this dependency type is not recognised by Dependabot, as far as I know.

🤖 call actionlint Docker image directly

---

.renovaterc.json5

At the moment, Renovate cannot find any updates to Rust crates as the changes would only affect `Cargo.lock` but not `Cargo.toml` such that it does not suggest any update PRs.  As even Dependabot updates are nothing more than a lock file maintenance, this PR turns the lock file maintenance feature on which Renovate allows for in order to have all Dependabot Rust updates bundled in a single PR per week.

🤖 allow for Renovate lock file maintenances

---

INSTALL.md
README.md

The PR updates the links in the docs and clarifies installation instructions.
The new step by step instructions aims to help users better understand the usage of required fonts.
It also moves the Arch linux installation instructions from the requirements to the installation section.

docs: clarify installation instructions

---

.github/workflows/lint.yml

As announced, this PR introduces a GHA to lint the Renovate configuration.  Changes to the Renovate setup will be submitted in a subsequent, separate PR.  The Action should succeed within usually 40 seconds.

🤖 add linting Action for Renovate configuration

---

.renovaterc.json5

This PR adjusts the schedules of Renovate's update cycles.
- By default (i.e., if there is no schedule defined), Renovate will run a Lock File Maintenance always "before 4am on monday".  I experienced this being somehow more reliable than my previous Cron setup.  Thus, I removed the explicit Cron schedule to rely on the implicit default.
- I set the implicit default of the Lock File Maintenance as the explicit value of the general schedule.  All updates, including Lock File Maintenances, should be in sync, now.

🤖 Renovate Schedule Fine-tuning

---

.renovaterc.json5

This PR removes the default hourly limit of at most two PRs being created per hour.  Removing this restriction will benefit the weekly auto-maintenance run.

🤖 Renovate:  disable hourly PR creation limit

---

README.md

I know that I some day named spacings as a reason to not use markdown badges when you mentioned them @kevinmatthes. With the preview in between the badges the spacing is okay I think 😊
I would merge this one before #249. The conflicts should not be too problematic to resolve.
The extended installation table was inspired by https://github.com/foresterre/cargo-msrv/

📝 update `README.md`

---

src/modules/weather.rs

An improved error message for historical weather data that is not yet available in open-meteo's archives. 
Resolves #135

fix: improve error message for not yet archived historical weather

---

.github/workflows/ci.yml

This will skip redundant runs in case there is a push to a branch on the origin repo that also has a PR associated with it.

🤖 add debounce step to skip obsolete runs on the origin repo in case there is a PR and a push to a branch

---

.github/workflows/ci.yml

Quick snip for a local repro help for potential future reference:
```sh
GITHUB_REPOSITORY="ttytm/wthrr-the-weathercrab"
GITHUB_REF_NAME="renovate/actions-upload-artifact-4.x" # a branch with a PR assiciated, should abort
pr_branches=$(gh pr list --json headRefName --repo "$GITHUB_REPOSITORY")
echo "pr_branches=$pr_branches"
echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
if [[ $(echo "$pr_branches" | jq -r --arg ref_name "$GITHUB_REF_NAME" '.[] | select(.headRefName == $ref_name)') ]]; then
echo "This push is associated with a pull request. Skipping the job."
echo "abort=true" >> "$GITHUB_OUTPUT"
fi
```

🤖 refine debounce

---

.github/workflows/ci.yml
.github/workflows/release.yml

Simplifies the workflow and serves as preparation for further extensions, like including a .deb artifact

🤖 refine release workflow

---

.github/workflows/release.yml

Updates release artifacts from e.g.:
- `wthrr-v1.1.1-x86_64-linux.tar.gz` to `wthrr-linux-x86_64`
- `wthrr-v1.1.1-x86_64-apple-darwin.tar.gz` to `wthrr-macos-x86_64`
The additional version specifications are removed from the file names since it is obsolete and even redundant, since the upload is already part of a tag/release with a dedicated version scope.
- This will allow to keep a single link to always get the latest stable release binary via the `releases/latest/download/` url, like:
[github.com/ttytm/wthrr-the-weathercrab/releases/latest/download/wthrr-linux-x86_64](https://github.com/ttytm/wthrr-the-weathercrab/releases/latest/download/wthrr-linux-x86_64)
- Or a specific version, like so:
[github.com/ttytm/wthrr-the-weathercrab/releases/download/v1.1.2/wthrr-linux-x86_64](https://git …

🤖 update artifact names

---

.github/workflows/release.yml

Adds a nightly release step.
This will also serve as a preliminary for an upcoming stable release and allow to verify that the updated release steps work after the recent updates.

🤖 add nightly release steps

---

.github/workflows/ci.yml
.github/workflows/release.yml

@ttytm
This PR fixes #348.  I replaced ``macos-11`` with the newer ``macos-12`` and ``macos-13`` settings.  Furthermore, in ``release.yml``, I also added further compilation targets such that MacOS versions 12 and 13 will both be targeted with ``x86_64`` as well as ``arm64`` architectures.
I would like to ask you to review these changes.

⬆️ update MacOS runner versions in GitHub CI pipeline

---

Cargo.lock
Cargo.toml
src/modules/display/current.rs
src/modules/display/day.rs
src/modules/display/historical.rs
src/modules/display/hourly.rs
src/modules/display/utils.rs
src/modules/display/week.rs

Resolves border bugs mentioned in #357
The enhancement regarding the translations the issue is mentioning will be tracked separately.

🐛 reimplement padding width calculation to fix border placement for languages with varying unicode character widths
